$ErrorActionPreference = 'Stop'
$baseUrl = 'http://127.0.0.1:8181/api/v1'
$examples = Join-Path $PSScriptRoot '..\ios-handoff\examples'
New-Item -ItemType Directory -Path $examples -Force | Out-Null

$password = ((Get-Content -LiteralPath (Join-Path $PSScriptRoot '..\.env') | Where-Object { $_ -like 'TRAINING_ADMIN_PASSWORD=*' }) -split '=', 2)[1]
$loginRequest = [ordered]@{ userName = 'taras'; password = $password }
$login = Invoke-RestMethod "$baseUrl/auth/login" -Method Post -ContentType 'application/json' -Body ($loginRequest | ConvertTo-Json)
$headers = @{ Authorization = "Bearer $($login.accessToken)" }

function Save-Json([string]$name, $value) {
    ConvertTo-Json -InputObject $value -Depth 30 | Set-Content -LiteralPath (Join-Path $examples $name) -Encoding UTF8
}
function Invoke-Json([string]$uri, [string]$method = 'Get', $body = $null) {
    $parameters = @{ Uri = $uri; Method = $method; Headers = $headers }
    if ($null -ne $body) { $parameters.ContentType = 'application/json'; $parameters.Body = (ConvertTo-Json -InputObject $body -Depth 20) }
    Invoke-RestMethod @parameters
}
function Invoke-Conflict([string]$uri, $body) {
    try { Invoke-Json $uri 'Post' $body | Out-Null; throw 'Expected conflict response' }
    catch {
        if ($null -eq $_.Exception.Response -or [int]$_.Exception.Response.StatusCode -ne 409) { throw }
        $reader = New-Object IO.StreamReader($_.Exception.Response.GetResponseStream())
        try { return ($reader.ReadToEnd() | ConvertFrom-Json) } finally { $reader.Dispose() }
    }
}

$workoutId = [Guid]::NewGuid()
$workoutExerciseId = [Guid]::NewGuid()
$plannedSetId = [Guid]::NewGuid()
$syncSetId = [Guid]::NewGuid()
$skippedSetId = [Guid]::NewGuid()
$scheduledAt = [DateTimeOffset]::UtcNow
$offlineCompletedAt = [DateTimeOffset]::UtcNow.AddMinutes(-15)

$createWorkoutRequest = [ordered]@{ id=$workoutId; name='iOS Handoff Verification'; scheduledAt=$scheduledAt.ToString('o'); notes='Generated by the documented handoff verification'; version=$null }
$createdWorkout = Invoke-Json "$baseUrl/workouts" 'Post' $createWorkoutRequest
Save-Json 'workout-create.request.json' $createWorkoutRequest
Save-Json 'workout-create.response.json' $createdWorkout

$updateWorkoutRequest = [ordered]@{ id=$workoutId; name='iOS Handoff Verification'; scheduledAt=$scheduledAt.ToString('o'); notes='Verified create and update'; version=$createdWorkout.version }
$updatedWorkout = Invoke-Json "$baseUrl/workouts/$workoutId" 'Put' $updateWorkoutRequest
Save-Json 'workout-update.request.json' $updateWorkoutRequest
Save-Json 'workout-update.response.json' $updatedWorkout

$exerciseRequest = [ordered]@{ id=$workoutExerciseId; exerciseId='11111111-1111-1111-1111-111111111111'; order=1; notes='Bench Press verification'; restSeconds=90 }
$exerciseResponse = Invoke-Json "$baseUrl/workouts/$workoutId/exercises" 'Post' $exerciseRequest
Save-Json 'workout-exercise-create.request.json' $exerciseRequest
Save-Json 'workout-exercise-create.response.json' $exerciseResponse

$plannedSetRequest = [ordered]@{ id=$plannedSetId; order=1; plannedWeightKg=60; plannedReps=8; actualWeightKg=$null; actualReps=$null; isWarmup=$false; notes='Direct set endpoint'; version=$null; status='Planned' }
$plannedSet = Invoke-Json "$baseUrl/workouts/$workoutId/exercises/$workoutExerciseId/sets" 'Post' $plannedSetRequest
Save-Json 'set-create.request.json' $plannedSetRequest
Save-Json 'set-create.response.json' $plannedSet

$startedWorkout = Invoke-Json "$baseUrl/workouts/$workoutId/start" 'Post'
Save-Json 'workout-start.response.json' $startedWorkout
$bootstrap = Invoke-Json "$baseUrl/bootstrap"
Save-Json 'bootstrap.response.json' $bootstrap

$completeSetRequest = [ordered]@{ id=$plannedSetId; order=1; plannedWeightKg=60; plannedReps=8; actualWeightKg=60; actualReps=8; isWarmup=$false; notes='Completed through set action'; version=$plannedSet.version; status='Completed' }
$completedSet = Invoke-Json "$baseUrl/workouts/$workoutId/sets/$plannedSetId/complete" 'Post' $completeSetRequest
Save-Json 'set-complete.request.json' $completeSetRequest
Save-Json 'set-complete.response.json' $completedSet

$syncCreateRequest = @([ordered]@{ id=$syncSetId; workoutExerciseId=$workoutExerciseId; expectedVersion=0; value=[ordered]@{ id=$syncSetId; order=2; plannedWeightKg=65; plannedReps=5; actualWeightKg=65; actualReps=5; isWarmup=$false; notes='Client-generated UUID'; version=$null; status='Completed'; completedAt=$offlineCompletedAt.ToString('o') } })
$syncCreated = Invoke-Json "$baseUrl/workouts/sync" 'Post' $syncCreateRequest
Save-Json 'sync-create.request.json' $syncCreateRequest
Save-Json 'sync-create.response.json' $syncCreated

$syncRetry = Invoke-Json "$baseUrl/workouts/sync" 'Post' $syncCreateRequest
Save-Json 'sync-retry.response.json' $syncRetry

$syncUpdateRequest = @([ordered]@{ id=$syncSetId; workoutExerciseId=$workoutExerciseId; expectedVersion=1; value=[ordered]@{ id=$syncSetId; order=2; plannedWeightKg=65; plannedReps=5; actualWeightKg=67.5; actualReps=5; isWarmup=$false; notes='Updated by sync'; version=1; status='Completed'; completedAt=$offlineCompletedAt.ToString('o') } })
$syncUpdated = Invoke-Json "$baseUrl/workouts/sync" 'Post' $syncUpdateRequest
Save-Json 'sync-update.request.json' $syncUpdateRequest
Save-Json 'sync-update.response.json' $syncUpdated

$syncConflict = Invoke-Conflict "$baseUrl/workouts/sync" $syncUpdateRequest
Save-Json 'sync-conflict.response-409.json' $syncConflict

$skipCreateRequest = [ordered]@{ id=$skippedSetId; order=3; plannedWeightKg=70; plannedReps=3; actualWeightKg=$null; actualReps=$null; isWarmup=$false; notes='Skip action verification'; version=$null; status='Planned' }
$skipCreated = Invoke-Json "$baseUrl/workouts/$workoutId/exercises/$workoutExerciseId/sets" 'Post' $skipCreateRequest
$skippedSet = Invoke-Json "$baseUrl/workouts/$workoutId/sets/$skippedSetId/skip" 'Post'
Save-Json 'set-skip.response.json' $skippedSet

$completedWorkout = Invoke-Json "$baseUrl/workouts/$workoutId/complete" 'Post'
Save-Json 'workout-complete.response.json' $completedWorkout
Save-Json 'workout-get.response.json' (Invoke-Json "$baseUrl/workouts/$workoutId")
Save-Json 'exercise-history.response.json' (Invoke-Json "$baseUrl/exercises/11111111-1111-1111-1111-111111111111/history")
Save-Json 'exercise-records.response.json' (Invoke-Json "$baseUrl/exercises/11111111-1111-1111-1111-111111111111/records")
Save-Json 'templates-list.response.json' (Invoke-Json "$baseUrl/templates")

$statsFrom = $offlineCompletedAt.AddMinutes(-1).ToString('o')
$statsTo = $offlineCompletedAt.AddMinutes(1).ToString('o')
$statistics = Invoke-Json "$baseUrl/statistics/volume?from=$([uri]::EscapeDataString($statsFrom))&to=$([uri]::EscapeDataString($statsTo))"
[pscustomobject]@{ WorkoutId=$workoutId; BootstrapWorkout=($bootstrap.workout.id -eq $workoutId); SyncCreate='200'; SyncRetry='200'; SyncUpdate='200'; SyncConflict='409'; OfflineCompletionPreserved=($statistics.totalVolumeKg -gt 0); WorkoutCompleted=($completedWorkout.status -eq 'Completed') }
